# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-12 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170205_1720'),
        ('users', '0004_auto_20170109_1534'),
    ]

    operations = [
    ]
