# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-12 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20170208_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseorg',
            name='course_nums',
        ),
        migrations.RemoveField(
            model_name='courseorg',
            name='students',
        ),
    ]
