# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-07 12:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u8ab2\u7a0b\u540d\u7a31')),
                ('desc', models.CharField(max_length=300, verbose_name='\u8ab2\u7a0b\u63cf\u8ff0')),
                ('detail', models.TextField(verbose_name='\u8ab2\u7a0b\u8a73\u60c5')),
                ('degree', models.CharField(choices=[('cj', '\u521d\u7d1a'), ('zj', '\u4e2d\u7d1a'), ('gj', '\u9ad8\u7d1a')], max_length=10)),
                ('learn_times', models.IntegerField(default=0, verbose_name='\u5b78\u7fd2\u6642\u5e38\uff08\u5206\u9418\u6578\uff09')),
                ('students', models.IntegerField(default=0, verbose_name='\u5b78\u7fd2\u4eba\u6578')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='\u6536\u85cf\u6578')),
                ('image', models.ImageField(default='image/', upload_to='image/%Y%m', verbose_name='\u5c01\u9762\u56fe')),
                ('click_nums', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6570')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u8bfe\u7a0b\u8868',
                'verbose_name_plural': '\u8bfe\u7a0b\u8868',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u7ae0\u8282\u540d')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='\u8bfe\u7a0b')),
            ],
            options={
                'verbose_name': '\u7ae0\u8282',
                'verbose_name_plural': '\u7ae0\u8282',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u89c6\u9891\u540d')),
                ('download', models.FileField(upload_to='course/resource/%Y/%m', verbose_name='\u4e0b\u8f7d')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='\u7ae0\u8282')),
            ],
            options={
                'verbose_name': '\u89c6\u9891',
                'verbose_name_plural': '\u89c6\u9891',
            },
        ),
    ]
