# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-05 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courseresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='degree',
            field=models.CharField(choices=[('cj', '\u521d\u7d1a'), ('zj', '\u4e2d\u7d1a'), ('gj', '\u9ad8\u7d1a')], max_length=10, verbose_name='\u8bfe\u7a0b\u96be\u5ea6'),
        ),
    ]
