# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-15 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tag',
            field=models.CharField(default='', max_length=20, verbose_name='\u5173\u952e\u8bcd'),
        ),
    ]
