# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-16 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.URLField(default='', verbose_name='\u4e0b\u8f7d\u5730\u5740'),
        ),
    ]
