# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-16 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(default='', max_length=200, verbose_name='\u4e0b\u8f7d\u5730\u5740'),
        ),
    ]
