# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-16 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20170216_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='learn_times',
            field=models.IntegerField(default=0, verbose_name='\u5b78\u7fd2\u6642\u5e38\uff08\u5206\u9418\u6578\uff09'),
        ),
    ]
